default: &default
  host:    localhost
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: CryptoName_development
  username: postgres
  password: 12345678
  template: template0

test:
  <<: *default
  encoding: unicode
  database: CryptoName_test
  username: postgres
  password: 12345678
  template: template0

staging:
  <<: *default
  database: CryptoName_staging
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
