default: &default
  host:     localhost
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: FastOrder_development
  username: postgres
  password: 12345678
  template: template0

test:
  <<: *default
  encoding: unicode
  database: FastOrder_test
  username: postgres
  password: 12345678
  template: template0

staging:
  <<: *default
  database: fullder_staging
  username: deploy
  password: "krisnikola2016"
  # password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: fullder_production
  username: deploy
  password: "krisnikola2016"
  # password: <%= ENV["DATABASE_PASSWORD"] %>
